[package]
name = "sg-solochain-node"
description = "A parachain node built with Substrate and Cumulus, part of Polkadot Sdk."
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
network_constants = { workspace = true }
sg-solochain-runtime = { workspace = true }

clap = { features = ["derive"], workspace = true }
futures = { features = ["thread-pool"], workspace = true }
jsonrpsee = { features = ["server"], workspace = true }

polkadot-sdk = { workspace = true, features = ["node"] }

[build-dependencies]
polkadot-sdk = { workspace = true, features = ["substrate-build-script-utils"] }

[features]
default = ["std"]
std = [
	"sg-solochain-runtime/std",
	"polkadot-sdk/std",
]
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"sg-solochain-runtime/runtime-benchmarks",
	"polkadot-sdk/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"sg-solochain-runtime/try-runtime",
	"polkadot-sdk/try-runtime",
]
